### ISSUE TITLE
error: unimplemented type 'list'

### ISSUE THREAD

**Issue by sarahcd** [movestore/rds2csv#16]
I'll share a workflow. Here is the full error message:
![image](https://github.com/movestore/rds2csv/assets/15783614/f74bb6d8-bb0f-4884-adb4-c541f4c3e79f)

**Comment by annescharf** [comment]
Hi @sarahcd , the version just released of the write csv app has this problem fixed.
Same as issue #13

**Comment by sarahcd** [comment]
Thanks! Tried it and I don't get that error message anymore, but get a different one. Will follow up separately.
