### ISSUE TITLE
duplicates of attributes

### ISSUE THREAD

**Issue by biolars** [movestore/rds2csv#2]
I am observing duplication of attributes in the output .csv file - with duplicates named *.1
This bloat the size of the table and the last makes it inconvenient to work with (looking for an attribute in two different columns).
Also, in the .csv the "Visible" attribute seems erroneously filled with the taxon! Visible.1 seems to have the original data.

Best regards,
Lars

**Comment by andreakoelzsch** [comment]
Hi Lars, thanks a lot for the feedback! Unfortunately, I cannot reproduce the behaviour that you are describing. Please, would you post here (or Email akoelzsch@ab.mpg.de) the rds file that comes out of the App just before the Write CSV App? (can also be some data subset, as long as it is causing the behaviour) Then I can see what is causing this behaviour. Best, Andrea

**Comment by andreakoelzsch** [comment]
Hi @biolars ,
I dont remember any more if we had resolved this issue, but we have now updated this "Write CSV" App to move2. It should not give duplicates apart from maybe the locations. Hope things are working out for you. Happy new year, Andrea

**Comment by biolars** [comment]
Hi Andrea!

I deleted the problematic workflow and have not have errors with the seemingly identical ones…
But thanks for letting me know!

Best regards,
Lars
