### ISSUE TITLE
update hard-coded names according to v1.5

### ISSUE THREAD

**Issue by andreakoelzsch** [movestore/rds2csv#5]
NOte that the move1 version of this APp has been updated to avoid hard-coded column names (Dec2023). [Fun fact: v1.4 is from Dec2021!!!] The move2 version is already there (but in a branch on not yet on www). DOnt forget to update it for this hard-coded column names avoidance before adding to www.

**Comment by annescharf** [comment]
See the last commit (https://github.com/movestore/rds2csv/commit/6a4912b1b5b709e8755b51143df44ff27f5426e6). As I was anyway at it I've adjusted the code, and when wanting to update the readme I realized that you produced 3 possible output tables. Lets talk about this in Jan :)

**Comment by andreakoelzsch** [comment]
merci :)
