### ISSUE TITLE
Issue with taxon_canonical_name in TrackInfo.csv

### ISSUE THREAD

**Issue by biolars** [movestore/rds2csv#7]
I just tested and there seems to be an issue with what is used for taxon_canonical_name in TrackInfo.csv. It shows as dates!

**Comment by annescharf** [comment]
Hi @biolars, thanks for letting us know. I'll fix it asap and let you know.

**Comment by annescharf** [comment]
With the next version of this app on moveapps, this problem should be fixed. Please reopen the issue if it persists. Thank you!

**Comment by biolars** [comment]
Hi Anne!
You are most welcome!
/L
________________________________
